on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # Add back other OS options after fix
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: xvfb-run -a npm run pretest
      if: runner.os == 'Linux'
    - run: npm run pretest
      if: runner.os != 'Linux'
